### ISSUE TITLE
Mira Mode Help!

### ISSUE THREAD

**Issue by kingal123** [dave01945/Car-PI#1]
Apologies for reaching out to you on another repository but was unable to comment on your forked version.
Would you be able to share how you managed to obtain the Device & Client IDs when you get 5 mins? I am new to BLE so trying to get my head around the Wireshark traffic I have captured. Many thanks.

**Comment by dave01945** [comment]
Have you captured a payload similar to this XX:87:05:01:01:90:64:00:YY:YY sent to chrateristic 11?

**Comment by kingal123** [comment]
Thanks so much for getting back to me - I haven't found a payload with the colons, the closest I have is as attached (20 characters) again are you able to help with where the characteristic 11 should be displayed?
[Wireshark Capture.pdf](https://github.com/dave01945/Car-PI/files/13401440/Wireshark.Capture.pdf)

**Comment by dave01945** [comment]
That looks correct the handle 0x0011 is the characteristic.

The colons are just to visually seperate the bytes they're not displayed in the value.

using the value you'll have a device id of 0x01 and a CRC 0x9f74. Once you generate the client id it can be used with the device id for control

**Comment by kingal123** [comment]
Brilliant thank you for confirming - last question I hope..! To generate the Client ID I noticed you have a crc16_loop python script. How do I enter the CRC/Device ID so it generates the Client ID?

**Comment by dave01945** [comment]
At the top of the python script are 2 byte arrays, you need to copy your value into these. data excludes the CRC and payl is the entire value.

Split the value into hex pairs so they look the same as below.

```
data = bytearray([
        0x01,
        0x87, 0x05,
        0x03,
        0x01,
        0x9a,
        0x00,
        0x00])
payl = bytearray([
        0x01,
        0x87, 0x05,
        0x03,
        0x01,
        0x9a,
        0x00,
        0x00,
        0xd5,0x28])
```

**Comment by kingal123** [comment]
Perfect have done that and believe the Client ID is 5559. With that info I have populated the python scripts in your repo however am receiving the following error at the end of the script executions: "pygatt.exceptions.NotConnectedError: Timed out connecting to c1:73:51:1a:08:ec after 1 seconds."
From the Wireshark snip previously provided this is definitely the correct BLE address would you agree?

**Comment by dave01945** [comment]
Yeah looks correct, make sure no other devices are connected otherwise it'll fail.

**Comment by kingal123** [comment]
All sorted - thank you so much for your help really appreciate it!
